# Generated by Django 3.2.20 on 2023-09-15 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_booked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booked',
            old_name='sname',
            new_name='level',
        ),
    ]
